-- Master skill library
insert into skills (skill_name, description, category) values
  ('Cloud Fundamentals', 'Core concepts of cloud computing.', 'cloud'),
  ('Cloud Infrastructure', 'Servers, data centers, and cloud infrastructure models.', 'cloud'),
  ('Compute', 'Virtual machines, instances, containers, serverless.', 'cloud'),
  ('Storage', 'Object, block, and file storage concepts.', 'cloud'),
  ('Networking', 'Regions, availability zones, data transfer.', 'cloud'),
  ('AWS Fundamentals', 'Core AWS services and concepts.', 'cloud'),
  ('Azure Fundamentals', 'Core Azure services and concepts.', 'cloud'),
  ('Google Cloud Fundamentals', 'Core GCP services and concepts.', 'cloud'),

  ('FinOps Fundamentals', 'What FinOps is and why it exists.', 'finops'),
  ('Cloud Billing', 'Reading and understanding cloud invoices.', 'finops'),
  ('Cost Allocation', 'Tagging, cost centers, showback/chargeback.', 'finops'),
  ('Tagging', 'Resource tagging strategy and hygiene.', 'finops'),
  ('Showback', 'Attributing cost visibility without billing.', 'finops'),
  ('Chargeback', 'Billing internal teams for cloud usage.', 'finops'),
  ('Budgeting', 'Creating and managing cloud budgets.', 'finops'),
  ('Forecasting', 'Projecting future cloud spend.', 'finops'),
  ('Variance Analysis', 'Explaining actual vs budget vs forecast gaps.', 'finops'),
  ('Cost Analysis', 'Analyzing spend trends and drivers.', 'finops'),
  ('Cost Optimization', 'Reducing waste and improving efficiency.', 'finops'),
  ('Rightsizing', 'Matching resource size to actual usage.', 'finops'),
  ('Storage Optimization', 'Lifecycle policies and storage class management.', 'finops'),
  ('Network Optimization', 'Reducing data transfer and egress costs.', 'finops'),
  ('Commitment Management', 'Reserved Instances, Savings Plans, CUDs.', 'finops'),
  ('Reserved Instances', 'AWS RI strategy and utilization.', 'finops'),
  ('Savings Plans', 'AWS Savings Plans strategy.', 'finops'),
  ('Committed Use Discounts', 'GCP/Azure commitment strategy.', 'finops'),
  ('Cost Anomaly Analysis', 'Investigating unexpected spend changes.', 'finops'),
  ('FinOps Governance', 'Policies, accountability, cost controls.', 'finops'),
  ('FinOps KPIs', 'Core FinOps metrics and their meaning.', 'finops'),
  ('Multi-Cloud FinOps', 'FinOps across AWS, Azure, and GCP.', 'finops'),
  ('Unit Economics', 'Cost per customer/transaction/workload.', 'finops'),
  ('Cloud Economics', 'ROI, TCO, and cloud investment decisions.', 'finops'),

  ('Excel', 'Spreadsheet analysis for FinOps reporting.', 'data'),
  ('Data Analysis', 'General data analysis skills.', 'data'),
  ('Cloud Cost Data Analysis', 'Analyzing cloud billing datasets.', 'data'),
  ('SQL Fundamentals', 'Querying billing data with SQL.', 'data'),
  ('Reporting', 'Building recurring cost reports.', 'data'),

  ('Problem Solving', 'Diagnosing and resolving cost problems.', 'professional'),
  ('Business Communication', 'Explaining findings in plain business terms.', 'professional'),
  ('Financial Analysis', 'Interpreting cost data in financial terms.', 'professional'),
  ('Executive Reporting', 'Communicating to leadership audiences.', 'professional'),
  ('Stakeholder Communication', 'Tailoring communication across audiences.', 'professional')
on conflict (skill_name) do nothing;
